// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiuarktentdjkxzgqtjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpdWFya3RlbnRkamt4emdxdGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NzEyNjAsImV4cCI6MjA2MDE0NzI2MH0.Ei8RA_Q1ZimDWifBElmeA3XoFvIvezlUsvhxzwoLbzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);